###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "estado": true,
  "posicion": "A11"
}
###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/AQUIVAELIDDELUSUARIO HTTP/1.1
//obtener los datos del usuario que quieras
###
DELETE http://localhost:9000/api/users/AQUIVAELIDDELUSUARIO HTTP/1.1
//eliminar el usuario que quieras
###
PUT http://localhost:9000/api/users/AQUIVAELIDDELUSUARIO HTTP/1.1
Content-Type: application/json
//actualizar datos de usuario que quieras
{
  "estado": true,
  "posicion": "B18"
}
